# Generated by Django 5.1.2 on 2024-11-08 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogentry",
            options={
                "ordering": ["created_at"],
                "permissions": [("can_unpublish_blogentry", "Can unpublish blogentry")],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
